"""Init

Revision ID: 28b5c23e6c5a
Revises: 
Create Date: 2025-03-13 18:50:20.674198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b5c23e6c5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_excel_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('xpath', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_excel_table_id'), 'user_excel_table', ['id'], unique=False)
    op.create_index(op.f('ix_user_excel_table_user'), 'user_excel_table', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_excel_table_user'), table_name='user_excel_table')
    op.drop_index(op.f('ix_user_excel_table_id'), table_name='user_excel_table')
    op.drop_table('user_excel_table')
    # ### end Alembic commands ###
